CREATE TABLE VATTU(
	MAVT CHAR(4) PRIMARY KEY,
	TENVT NVARCHAR(50),
	DVTINH NUMERIC,
	SLCON INT,
)
GO

CREATE TABLE HDBAN(
	MAHD NVARCHAR(10) PRIMARY KEY,
	NGAYXUAT SMALLDATETIME,
	HOTENKHACH NVARCHAR(50)
)
GO

CREATE TABLE HANGXUAT(
	MAHD NVARCHAR(10),
	MAVT CHAR(4),
	DONGIA MONEY,
	SLBan INT,
	CONSTRAINT pk_hx PRIMARY KEY(MAHD, MAVT)
)
GO

---> Câu 1
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUE (N'VT01', N'XI MANG', 'VND', 100)
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUE(N'VT02', N'CAT', 'VND', 200)
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHAC) VALUE(N'HD0058',CAST(N'2022-10-3'AS DATE),N'NGUYEN VAN A')
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHAC) VALUE(N'HD0064',CAST(N'2022-9-5'AS DATE),N'DO HOANG B')
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUE(N'HD0058',N'VT01',100000, 200)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUE(N'HD0059',N'VT01',200000, 400)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUE(N'HD0061',N'VT02',100000, 300)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUE(N'HD0062',N'VT02',100000, 100)

---> Câu 2
SELECT TOP 1 (SLBAN* DONGIA) AS 'tong tien ', MAHD 
 FROM  HANGXUAT
 ORDER BY [tong tien ] DESC

---> Câu 3
CREATE FUNCTION f3 (
    @MAHD varchar(10)
)
RETURNS TABLE
AS
RETURN
    SELECT 
        HX.MAHD,
        HD.NGAYXUAT,
        HD.MAVT,
        HX.DONGIA,
        HX.SLBAN,  
        CASE
            WHEN WEEKDAY(HD.NGAYXUAT) = 0 THEN N'Thứ hai'            
            WHEN WEEKDAY(HD.NGAYXUAT) = 1 THEN N'Thứ ba'
            WHEN WEEKDAY(HD.NGAYXUAT) = 2 THEN N'Thứ tư'
            WHEN WEEKDAY(HD.NGAYXUAT) = 3 THEN N'Thứ năm'
            WHEN WEEKDAY(HD.NGAYXUAT) = 4 THEN N'Thứ sáu'
            WHEN WEEKDAY(HD.NGAYXUAT) = 5 THEN N'Thứ bảy'
            ELSE N'Chủ nhật'
        END AS NGAYTHU
    FROM HANGXUAT HX
    INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
    WHERE HX.MAHD = @MAHD;
---> Câu 4
CREATE PROCEDURE p4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;
bé vô tri
select top 1 MAHD, sum(DONGIA) as TongTien from HANGXUAT group by MAHD,
DONGIA order by DONGIA desc

